
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ADMINISTRATEUR
export const CREATE_ADMINISTRATEUR_SUCCESS = "CREATE_ADMINISTRATEUR_SUCCESS";
export const DELETE_ADMINISTRATEUR_SUCCESS = "DELETE_ADMINISTRATEUR_SUCCESS";
export const GET_ADMINISTRATEUR_SUCCESS = "GET_ADMINISTRATEUR_SUCCESS";
export const LIST_ADMINISTRATEUR_SUCCESS = "LIST_ADMINISTRATEUR_SUCCESS";
export const UPDATE_ADMINISTRATEUR_SUCCESS = "UPDATE_ADMINISTRATEUR_SUCCESS";

// ETUDIANT
export const CREATE_ETUDIANT_SUCCESS = "CREATE_ETUDIANT_SUCCESS";
export const DELETE_ETUDIANT_SUCCESS = "DELETE_ETUDIANT_SUCCESS";
export const GET_ETUDIANT_SUCCESS = "GET_ETUDIANT_SUCCESS";
export const LIST_ETUDIANT_SUCCESS = "LIST_ETUDIANT_SUCCESS";
export const UPDATE_ETUDIANT_SUCCESS = "UPDATE_ETUDIANT_SUCCESS";

// PROFESSEUR
export const CREATE_PROFESSEUR_SUCCESS = "CREATE_PROFESSEUR_SUCCESS";
export const DELETE_PROFESSEUR_SUCCESS = "DELETE_PROFESSEUR_SUCCESS";
export const GET_PROFESSEUR_SUCCESS = "GET_PROFESSEUR_SUCCESS";
export const LIST_PROFESSEUR_SUCCESS = "LIST_PROFESSEUR_SUCCESS";
export const UPDATE_PROFESSEUR_SUCCESS = "UPDATE_PROFESSEUR_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
